#!/bin/sh
sed -e '
	s/。/．/g
	s/、/，/g
	s/!\[\([^#]*\)#fig:\([^]]*\)\](\([^)]*\))/\\figureimage{\1}{fig:\2}{\3}/g
	s/!\[\([^#]*\)#tbl:\([^{]*\){\([^}]*\)}\](\([^)]*\))/\\loadtable{\1}{tbl:\2}{\3}{\4}/g
	s/\[@bib:\([^]]*\)\]/\\cite{\1}/g
	s/^```\([^:]*\):\([^{]*\){\s*#\([^}]*\)}$/\\begin{code}[\3]{\2}\\begin{verbatim}/g
	s/^```$/\\end{verbatim}\\end{code}/g
	'
